### ISSUE TITLE
chia矿池吗？

### ISSUE THREAD

**Issue by zheng9980419** [Playwo/ChiaPool#1]
有联系方式嘛？

**Comment by Playwo** [comment]
Yes you can contact me on [discord](https://discord.gg/FymKQeF26e)
But I only understand german & english

**Comment by honyet** [comment]
> 有联系方式嘛？

老兄，搞得怎么样了，数据库我还没搞定，这个是不是不能加陌生矿工?

**Comment by Playwo** [comment]
@honyet Please do the following:
1. Open a issue, don't post on already closed ones with something new
2. Use english because I do not understand chinese

**Comment by z1017371914** [comment]
> > 有联系方式嘛？
> 
> 老兄，搞得怎么样了，数据库我还没搞定，这个是不是不能加陌生矿工?

老哥，能留个联系方式吗？交流一下怎么构建pool
