### ISSUE TITLE
Unhandled exception. System.Exception: Chia responded with unsuccessful

### ISSUE THREAD

**Issue by musik** [Playwo/ChiaPool#10]
Got this message when I run `$ docker-compose up`

---

ChiaNode   | Starting daemon
ChiaNode   | chia_wallet: started
ChiaNode   | chia_full_node: started
ChiaNode   | info: ChiaPool.Startup[0]
ChiaNode   |       Waiting for wallet to spin up
ChiaNode   | info: ChiaPool.Startup[0]
ChiaNode   |       Connection established!
ChiaNode   | No online backup file found,
ChiaNode   |  Press S to skip restore from backup
ChiaNode   |  Press F to use your own backup file: Exception from 'wallet' 'not_initialized'
ChiaNode   | info: ChiaPool.Startup[0]
ChiaNode   |       Waiting for fullnode to spin up
ChiaNode   | info: ChiaPool.Startup[0]
ChiaNode   |       Connection established!
ChiaNode   | Unhandled exception. System.Exception: Chia responded with unsuccessful
ChiaNode   |    at Chia.NET.Clients.ChiaApiClient.PostAsync[T](Uri requestUri, IDictionary`2 parameters) in /root/ChiaPool/Api/Chia.NET/Clients/ChiaApiClient.cs:line 65
ChiaNode   |    at Chia.NET.Clients.WalletClient.GetWalletAddressAsync(Int32 walletId, Boolean generateAddress) in /root/ChiaPool/Api/Chia.NET/Clients/Wallet/WalletClient.cs:line 35
ChiaNode   |    at ChiaPool.Services.WalletService.InitializeAsync() in /root/ChiaPool/ChiaPool.Server/Services/WalletService.cs:line 21
ChiaNode   |    at Common.Extensions.Extensions.InitializeApplicationServicesAsync(IServiceProvider provider, Assembly assembly)
ChiaNode   |    at ChiaPool.Program.Main(String[] args) in /root/ChiaPool/ChiaPool.Server/Program.cs:line 59
ChiaNode   |    at ChiaPool.Program.<Main>(String[] args)
ChiaNode   | ./entrypoint.sh: line 31:  1492 Aborted                 ./ChiaPool.Server

---

Thanks.

**Comment by Playwo** [comment]
I know about this issue. It's not on your end. Please wait a bit, I'll comment when I have fixed it

**Comment by Playwo** [comment]
Fixed, rebuild your image :)
