### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by adrielpereira** [Playwo/ChiaPool#13]
I'm try to running the server project out of docker,  I set all the hardcoded  and environment variables, in debug mode find the certificate create the httpclint handler, but throw this exception.

Anyone try to run the server out the docker? on Windows 10

**Comment by Playwo** [comment]
Running outside of docker is not possible without changing the code. E.g. I have hardcoded some paths.
If you want to do these changes it's all up to you.

Can you maybe specify where this error is occuring?

**Comment by adrielpereira** [comment]
I have change all the paths to my local path and set the environment variables, I got this error on Program.cs method WaitForChiaClientAsync I think that is to test the connection with the full_node. I'm runnning the full node local, it's already synced and farming.

**Comment by Playwo** [comment]
Contacting the rpc interfaces requires certificates. On linus they are in /root/.chia/mainnet/config/ssl. On windows they should be in %userprofile%/.chia/mainnet/config/ssl. Seems like you missed changing [that path](https://github.com/Playwo/ChiaPool/blob/master/Api/Chia.NET/Clients/ChiaApiClient.cs#L15) in the code.

**Comment by Playwo** [comment]
It might also be that the certificates in that folder don't work with the rpc interfaces. I had issues with that before but I don't know if that is still a thing

**Comment by adrielpereira** [comment]
> Contacting the rpc interfaces requires certificates. On linus they are in /root/.chia/mainnet/config/ssl. On windows they should be in %userprofile%/.chia/mainnet/config/ssl. Seems like you missed changing [that path](https://github.com/Playwo/ChiaPool/blob/master/Api/Chia.NET/Clients/ChiaApiClient.cs#L15) in the code.

The path is correct, I debug the code then found the cert load and add to the httpclient handler. I will try to copy the ssl's folder to another path and test.

**Comment by adrielpereira** [comment]
I found the solution need to generate for all the certificates farmer, full_node, wallet and harvester the pfx certificate file join crt and key,
 I used openssl to do it then change in ChiaApiClient.cs the import in method  InitializeAsync to :
string certificatePath = Path.Combine(SslDirectory, CertName, $"private_{CertName}.pfx");
X509Certificate2 certificate = new X509Certificate2(certificatePath, "password", X509KeyStorageFlags.Exportable);

**Comment by Playwo** [comment]
Hmm ok, good to know. Weird that it works on linux without using a pfx. 
Will close the issue now that you solved it
