### ISSUE TITLE
how to set up db_connection ?

### ISSUE THREAD

**Issue by EthanHee** [Playwo/ChiaPool#14]
hi, would you provide the steps to install the db and  the example  setting of  db_connection please?

and the db table  structure？

**Comment by Playwo** [comment]
When installing postgres you should stick to the [dockerhub entry](https://hub.docker.com/_/postgres)
The compose section is especially useful. A full guide on that will appear in the installation wiki in a few days.

A connection string looks like this: "Host=myDbAddress;Database=Pool;Username=myUserName;Password=myPassWord"

You don't need to interact with the table structure anymore, everything can be done with the CLI.
