### ISSUE TITLE
Can you provide a running step？

### ISSUE THREAD

**Issue by zheng9980419** [Playwo/ChiaPool#2]

**Comment by Playwo** [comment]
Currently the project is still in a early state and very unstable.
Once I get it to a more stable and finalized state I will publish current docker images along with installation instructions for each of the applications there and here in the repository. It should be in a few days

**Comment by zheng9980419** [comment]
Okay, verygood

**Comment by zheng9980419** [comment]
Percentage

**Comment by Playwo** [comment]
I'd say about 80%. Miner, Server and CLI Interface are in a usable state. The biggest missing piece is the plotter which I need to generate plots on servers and automatically move them to my miners. 
Currently there are still a few things hardcoded for ease of development, I will remove them and add some considerations about running this to the readme later today.

**Comment by zheng9980419** [comment]
Please provide a database example

**Comment by zheng9980419** [comment]
Oh i see the table structure

**Comment by zheng9980419** [comment]
Need to run all nodes?
Run only farm?

**Comment by Playwo** [comment]
The server will run all nodes while the miner only runs the harvester. All functionality of the other nodes that might be required can be accessed via the ChiaPool CLI

**Comment by zheng9980419** [comment]
OK, I'll start using this version

**Comment by zheng9980419** [comment]
Can you give us an example of database installation

**Comment by Playwo** [comment]
There will still be a lot of changes down the line but the current version should be stable enough to use (I have it running all the time now) 
For the database install [postgres](https://www.postgresql.org/download/) and put the connectionstring into the env file of the server.
e.g. Host=mydb.de;Database=____;Username=____;Password=____

**Comment by zheng9980419** [comment]
Thank you very much.

**Comment by Playwo** [comment]
You will also need to manually add users and miners / plotter to the database, that bit is not yet possible with the CLI

**Comment by zheng9980419** [comment]
Can I access your UI page?

**Comment by Playwo** [comment]
UI? There is none so far, I'm not sure if I will add a UI to the webinterface at some point. 
You can set the CLI to my pool to give it a test. It is in the Interface projects, if you don't know how to build I can provide you with a current build. 
My pool address is https://pool.playwo.de

**Comment by zheng9980419** [comment]
thank you very much. I'll deploy first. I'll contact you when I have problems。

**Comment by honyet** [comment]
> thank you very much. I'll deploy first. I'll contact you when I have problems。

我表结构搞得不对，运行不起来，你运行起来了吗？
My table structure is wrong and it can't run. Are you running?

**Comment by Playwo** [comment]
What do you mean by wrong table structure? Any exceptions? What is the issue?

**Comment by Playwo** [comment]
I have created a wiki page about the installation, it's still very much incomplete but I'll continue add to it

**Comment by honyet** [comment]
I look your code with created the data structure. Maybe structure not quite right

**Comment by zheng9980419** [comment]
root@ipfs100x20:~/manager# ./ChiaPool.Server
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {2e6278d0-1776-44f3-929b-ec6b5329a209} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:8666
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/manager

**Comment by Playwo** [comment]
@honyet What exactly? The model is fine and works as expected for me

**Comment by Playwo** [comment]
@zheng9980419 You can ignore that warning, it does not affect functionality. I will fix it later.
Also make sure to run it in the docker environment because it relies on the local chia rpc interfaces.

**Comment by zheng9980419** [comment]
How to set token？

**Comment by Playwo** [comment]
You will need to connect to the database manually (e.g. with pgadmin) and add a user and miner. 
Will add this to the CLI later

**Comment by zheng9980419** [comment]
Give me an example of table data. It's better to import a file directly？

**Comment by zheng9980419** [comment]
chiadb=> select * from "Miners";
 Id | Name | Token | Earnings | OwnerId 
----+------+-------+----------+---------
(0 rows)

chiadb=> select * from "Users";
 Id | Name | PasswordHash | PlotMinutes

**Comment by zheng9980419** [comment]
What is the relationship？

**Comment by zheng9980419** [comment]
framework:
2 servers,
poolserver
Miner server, how to connect the database, can't find the token data

**Comment by Playwo** [comment]
You don't need to connect from miner server, the token is transferred in the handshake between pool and miner.
There is no method that creates miners/users yet therefore you will need to set everything yourself.
You can use a [Guid Generator](https://www.guidgenerator.com/) for the token and a [Sha512 Calculator](https://emn178.github.io/online-tools/sha512.html) for the password.
Example data:
User:
<img src="https://s.playwo.de/v/zYoiJ"/>

Miner:
<img src="https://s.playwo.de/v/lvy4H"/>

**Comment by zheng9980419** [comment]
root@ipfs100x163:~/manager# ./ChiaPool.Miner init
fail: ChiaPool.Startup[0]
      Config Validation failed: Miner token has invalid format!

**Comment by zheng9980419** [comment]
chiadb=> select * from "Miners";
 Id | Name  |                Token                 | Earnings | OwnerId 
----+-------+--------------------------------------+----------+---------
  1 | jerry | 801d6fbd-afb8-4cf8-811c-ca904953fd54 |        0 |       1

**Comment by zheng9980419** [comment]
Id | Name  | PasswordHash | PlotMinutes 
----+-------+--------------+-------------
  1 | jerry | 13524600     |           0

**Comment by zheng9980419** [comment]
./ChiaPool.Miner init
fail: ChiaPool.Startup[0]
      Config Validation failed: Could not parse pool host "192.168.100.20" to URL

**Comment by zheng9980419** [comment]
80 port? I didn't see pool on 80

**Comment by zheng9980419** [comment]
(venv) root@ipfs100x163:~/manager# ./ChiaPool.Miner
info: ChiaPool.Startup[0]
      Waiting for harvester to spin up
warn: ChiaPool.Startup[0]
      Connection failed. Trying again in 5 seconds. 9 retries left
warn: ChiaPool.Startup[0]
      Connection failed. Trying again in 5 seconds. 8 retries left
warn: ChiaPool.Startup[0]
      Connection failed. Trying again in 5 seconds. 7 retries left
warn: ChiaPool.Startup[0]
      Connection failed. Trying again in 5 seconds. 6 retries left

**Comment by zheng9980419** [comment]
fail: ChiaPool.Startup[0]
      Failed connecting to chia!
      System.Text.Json.JsonException: The JSON value could not be converted to System.Net.IPAddress. Path: $.connections[0].peer_host | LineNumber: 0 | BytePositionInLine: 273.
         at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
         at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
         at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Chia.NET.Clients.ChiaApiClient.PostAsync[T](Uri requestUri, IDictionary`2 parameters) in /root/ChiaPool/Api/Chia.NET/Clients/ChiaApiClient.cs:line 63
         at Chia.NET.Clients.ChiaApiClient.GetConnections() in /root/ChiaPool/Api/Chia.NET/Clients/ChiaApiClient.cs:line 50
         at ChiaPool.Program.WaitForHarvesterAsync() in /root/ChiaPool/ChiaPool.Miner/Program.cs:line 146

**Comment by zheng9980419** [comment]
(venv) root@ipfs100x163:~/.chia/mainnet/config/ssl/harvester# curl --insecure --cert ~/.chia/mainnet/config/ssl/harvester/private_harvester.crt \
> --key ~/.chia/mainnet/config/ssl/harvester/private_harvester.key \
> -d '{"":""}' -H "Content-Type: application/json" -X POST https://localhost:8560/get_connections
{"connections": [{"bytes_read": 1638499, "bytes_written": 1696944, "creation_time": 1618717085.240463, "last_message_time": 1618892767.090015, "local_port": 8448, "node_id": "0x891c15e0eb688ef2464315553c9f90e58062fb2222ba775069441c3ac97455c8", "peer_host": "192.168.100.20", "peer_port": 8447, "peer_server_port": 8447, "type": 3}], "success": true}(venv)

**Comment by Playwo** [comment]
Looks like a parsing issue, I don't know why it fails to parse `192.168.100.20` because it looks like a valid ip to me...
Will do some testing and push a patch later today

**Comment by zheng9980419** [comment]
Unable to access cli

**Comment by zheng9980419** [comment]
Plotters 
PlotTransfers
What is the purpose and when will the data be inserted？

**Comment by zheng9980419** [comment]
select * from "Miners";
 Id | Name  |                Token                 | Earnings | OwnerId 
----+-------+--------------------------------------+----------+---------
  1 | jerry | 801d6fbd-afb8-4cf8-811c-ca904953fd54 |    11580 |       1

**Comment by zheng9980419** [comment]
select * from "Users";
 Id | Name  | PasswordHash | PlotMinutes 
----+-------+--------------+-------------
  1 | jerry | 13524600     |       11580

**Comment by zheng9980419** [comment]
select * from "PlotTransfers";
 Id | PlotterId | PlotId | MinerId | Cost | DownloadAddress | Deadline 
----+-----------+--------+---------+------+-----------------+----------
(0 rows)

**Comment by zheng9980419** [comment]
select * from "Plotters";
 Id | Name | Token | Earnings | OwnerId 
----+------+-------+----------+---------
(0 rows)

**Comment by Playwo** [comment]
> Plotters
> PlotTransfers
> What is the purpose and when will the data be inserted？

Plotters are machines that don't mine and just create plot files and serve them to the network. Miners can "buy" PlotTransfers for PM (Plot Minutes) to get a download url to a plot file on a plot machine. I added that to be able to give plots to friends who do not want to damage their SSD but still want to mine. 
You could also use that to move plots from your own plotter to your own miner (setting the plot price to 0) if they share a network.

**Comment by zheng9980419** [comment]
select * from "Miners";
 Id | Name  |                Token                 | Earnings | OwnerId 
----+-------+--------------------------------------+----------+---------
  1 | jerry | 801d6fbd-afb8-4cf8-811c-ca904953fd54 |    62100 |       1
  2 | jack  | 207c3d44-1dd6-4623-ab18-4b02494c06d2 |    74112 |       1
  
  Earnings Will there be forgery??

**Comment by Playwo** [comment]
If you are hosting the pool server you can modify values. The earnings are just a visual thing tho. 
The "real" earnings value in in the user. 
This pool requires trust and this is one of the reasons why. I'm trying to change that but it is not easy

**Comment by zheng9980419** [comment]
curl http://localhost:8666/Pool/Info
{"name":"ChiaPool","totalMinerCount":2,"activeMinerCount":2,"minerPlots":454,"totalPlotterCount":0,"activePlotterCount":0,"plotterCapactity":0,"plotterPlots":0,"totalPlotMinutes":186606}

plotterCapactity
 Does the miner have capacity?
Why can't you see it

**Comment by Playwo** [comment]
The thing you are looking for is this : `"minerPlots":454`

**Comment by Playwo** [comment]
@zheng9980419 Is your IP address in the server logs? 
There is no proper error message yet if the ip could not be whitelisted and it can appear as if everything works but it does not.

**Comment by SametBasturkk** [comment]
> > Plotters
> > PlotTransfers
> > What is the purpose and when will the data be inserted？
> 
> Plotters are machines that don't mine and just create plot files and serve them to the network. Miners can "buy" PlotTransfers for PM (Plot Minutes) to get a download url to a plot file on a plot machine. I added that to be able to give plots to friends who do not want to damage their SSD but still want to mine.
> You could also use that to move plots from your own plotter to your own miner (setting the plot price to 0) if they share a network.
> Plotters are not fully implemented yet, you cannot use them yet.
> 
> The Plotters table work exactly like the Miners table, just a different type of "pool node". The PlotTransfer table is managed by the pool server software, you don't have to touch it.

If you finish that Im sure I can find many buyers to you  :D

**Comment by Playwo** [comment]
@zheng9980419 I fixed the parsing issue, try rebuilding the image

**Comment by Playwo** [comment]
Will close this for now. Please create new issues and look through existing ones if you encounter any errors.

**Comment by github332638015** [comment]
ChiaNode | Chia directory /root/.chia/mainnet
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | /root/.chia/mainnet already exists, no migration action taken
ChiaNode | Enter the mnemonic you want to use: Invalid mnemonic length
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
ChiaNode |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
ChiaNode |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
ChiaNode |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
ChiaNode |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
ChiaNode |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
ChiaNode |    at System.Threading.Tasks.Task.FinishContinuations()
ChiaNode |    at System.Threading.Tasks.Task.FinishStageThree()
ChiaNode |    at System.Threading.Tasks.Task.FinishStageTwo()
ChiaNode |    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
ChiaNode |    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
ChiaNode |    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetException(Exception exception)
ChiaNode |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
ChiaNode |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
ChiaNode |    at System.Threading.ThreadPool.<>c.<.cctor>b__60_0(Object state)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.WriteOperation.System.Threading.IThreadPoolWorkItem.Execute()
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
ChiaNode |    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
ChiaNode |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
ChiaNode |    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
ChiaNode | --- End of stack trace from previous location ---
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
ChiaNode | --- End of stack trace from previous location ---
ChiaNode |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
ChiaNode |    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
ChiaNode |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
ChiaNode |    at ChiaPool.Program.MigrateDatabaseAsync() in /root/ChiaPool/ChiaPool.Server/Program.cs:line 92
ChiaNode |    at ChiaPool.Program.Main(String[] args) in /root/ChiaPool/ChiaPool.Server/Program.cs:line 38
ChiaNode |    at ChiaPool.Program.<Main>(String[] args)
ChiaNode | ./entrypoint.sh: line 27:    19 Aborted                 (core dumped) ./ChiaPool.Server init

**Comment by github332638015** [comment]
ChiaNode | Chia directory /root/.chia/mainnet
ChiaNode | Can't find private CA, creating a new one in /root/.chia/mainnet to generate TLS certificates
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | 
ChiaNode | To see your keys, run 'chia keys show'
ChiaNode | Enter the mnemonic you want to use: Invalid mnemonic length
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for wallet to spin up

**Comment by github332638015** [comment]
ChiaNode | Chia directory /root/.chia/mainnet
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | /root/.chia/mainnet already exists, no migration action taken
ChiaNode | Enter the mnemonic you want to use: Invalid mnemonic length
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for wallet to spin up
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Connection established!
ChiaNode | No keys loaded. Run 'chia keys generate' or import a key
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for fullnode to spin up
