### ISSUE TITLE
No web page was found for the web address:

### ISSUE THREAD

**Issue by sachinbanugariya** [Playwo/ChiaPool#22]
after setup pool and dokcer-compose up, it started listening on 8666,
then we setup nginx proxy pass, and frontend side when we try to open url its not showing anything and gives error:
No web page was found for the web address

also in backend there is not seems any error for this.
can anyone help on this issue.
thanks

**Comment by Playwo** [comment]
The pool does not come with a website. 
It only comes with a API you can interact with using REST or the CLI application that is included in this repo
