### ISSUE TITLE
thank s

### ISSUE THREAD

**Issue by grandfatheryun** [Playwo/ChiaPool#3]
that's i star! 
please give more information about how to make a pow pool
i want to run a person xch pool
thank you so much

**Comment by Playwo** [comment]
I will add a few information about running this today (there are some considerations to be made). But you cannot selfhost it just yet because I still have to remove some hardcoded urls and fix some other issues

**Comment by grandfatheryun** [comment]
can i ask you something about run chia？can i use more than 4 pieces of hdd to make a raid0.so i just plot it once? can it save my time? and how can my hdd continue to mine the chia? thank for your support!

**Comment by Playwo** [comment]
For questions about running chia (not this pooling software) you should ask on their [Keybase](https://keybase.io/team/chia_network.public).
But answering your question, if you put HDDs into Raid0 you will increase your plotting (not mining) speed significantly up to the point where some other component starts to be the limiting factor (RAM/CPU/Whatever). For mining you just have to move the plot files into a plot directory of your harvester and it will automatically find and use it.

**Comment by grandfatheryun** [comment]
thkssssssss
