### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by zheng9980419** [Playwo/ChiaPool#7]
Starting A high performance web server and a reverse proxy server...
Apr 23 13:29:08 iZbp16s66e1t3b5tzsshflZ systemd[1]: Started A high performance web server and a reverse proxy server.
Apr 23 13:36:09 iZbp16s66e1t3b5tzsshflZ systemd[1]: Reloading A high performance web server and a reverse proxy server.
Apr 23 13:36:09 iZbp16s66e1t3b5tzsshflZ nginx[967563]: nginx: [emerg] unknown "connection_upgrade" variable
Apr 23 13:36:09 iZbp16s66e1t3b5tzsshflZ systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 23 13:36:09 iZbp16s66e1t3b5tzsshflZ systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
root@iZbp16s66e1t3b5tzsshflZ:~/manager# /etc/init.d/nginx stop
Stopping nginx (via systemctl): nginx.service.
root@iZbp16s66e1t3b5tzsshflZ:~/manager# /etc/init.d/nginx reload
Reloading nginx configuration (via systemctl): nginx.servicenginx.service is not active, cannot reload.
 failed!
root@iZbp16s66e1t3b5tzsshflZ:~/manager# /etc/init.d/nginx start
Starting nginx (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
 failed!

**Comment by zheng9980419** [comment]
proxy_set_header   Connection $connection_upgrade;

**Comment by Playwo** [comment]
Oh yeah my bad, forgot to add a part to the installation wiki. 
Thanks for reporting, look at the modified wiki for the missing part
