### ISSUE TITLE
  How to set connection string？？？

### ISSUE THREAD

**Issue by tancau** [Playwo/ChiaPool#8]
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
ChiaNode |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
ChiaNode |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
ChiaNode |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
ChiaNode |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
ChiaNode |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
ChiaNode |    at System.Threading.Tasks.Task.FinishContinuations()
ChiaNode |    at System.Threading.Tasks.Task.FinishStageThree()
ChiaNode |    at System.Threading.Tasks.Task.FinishStageTwo()
ChiaNode |    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
ChiaNode |    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
ChiaNode |    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetException(Exception exception)
ChiaNode |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
ChiaNode |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
ChiaNode |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
ChiaNode |    at System.Threading.ThreadPool.<>c.<.cctor>b__60_0(Object state)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
ChiaNode |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
ChiaNode |    at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.WriteOperation.System.Threading.IThreadPoolWorkItem.Execute()
ChiaNode |    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
ChiaNode |    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
ChiaNode |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
ChiaNode |    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
ChiaNode | --- End of stack trace from previous location ---
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
ChiaNode |    at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
ChiaNode | --- End of stack trace from previous location ---
ChiaNode |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
ChiaNode |    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
ChiaNode |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
ChiaNode |    at ChiaPool.Program.MigrateDatabaseAsync() in /root/ChiaPool/ChiaPool.Server/Program.cs:line 92
ChiaNode |    at ChiaPool.Program.Main(String[] args) in /root/ChiaPool/ChiaPool.Server/Program.cs:line 38
ChiaNode |    at ChiaPool.Program.<Main>(String[] args)
ChiaNode | ./entrypoint.sh: line 27:   888 Aborted                 (core dumped) ./ChiaPool.Server init
ChiaNode exited with code 134

db_connection="database=chiadb;username=chiadb;password=178255;host=localhost;port=5432;"

**Comment by Playwo** [comment]
The pool server runs in docker. localhost will not point to the host on your machine outside of docker. 
Make sure that the container can access the database on the address specified in the connection string

**Comment by tancau** [comment]
@Playwo 
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for fullnode to spin up
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Connection established!
ChiaNode | Unhandled exception. System.Exception: Chia responded with unsuccessful
ChiaNode |    at Chia.NET.Clients.ChiaApiClient.PostAsync[T](Uri requestUri, IDictionary`2 parameters) in /root/ChiaPool/Api/Chia.NET/Clients/ChiaApiClient.cs:line 65
ChiaNode |    at Chia.NET.Clients.WalletClient.GetWalletAddressAsync(Int32 walletId, Boolean generateAddress) in /root/ChiaPool/Api/Chia.NET/Clients/Wallet/WalletClient.cs:line 35
ChiaNode |    at ChiaPool.Services.WalletService.InitializeAsync() in /root/ChiaPool/ChiaPool.Server/Services/WalletService.cs:line 21
ChiaNode |    at Common.Extensions.Extensions.InitializeApplicationServicesAsync(IServiceProvider provider, Assembly assembly)
ChiaNode |    at ChiaPool.Program.Main(String[] args) in /root/ChiaPool/ChiaPool.Server/Program.cs:line 59
ChiaNode |    at ChiaPool.Program.<Main>(String[] args)
ChiaNode | ./entrypoint.sh: line 31:  1495 Aborted                 (core dumped) ./ChiaPool.Server

**Comment by Playwo** [comment]
I know about this error. I hope I can fix it this evening (In at most 6 hours)
This is not on your end

**Comment by cqcwasd** [comment]
I also encountered the same problem and don't know how to configure pool.env
Is this configuration correct?
-----------------------------------------------------------------------------------------------
# Name of the pool, can be any string
pool_name=chiapool
# Key of the wallet, keep these secure
wallet_keys=0xa0ea3cb47d31e328976caf396052d217727a5f09c761e2ebc2a17cf8765c9b409b9b1a1fa476d48279e1d9fff6ef75a5
# Keys used for plotting and farming, those are available to the harvesters, do not use the wallet key for this
farmer_keys=0x81a8979ef2604ed706b070140108efbc67c309b3c262f88d04219dd50355aa4d22fa8cb8ea3fc1b933ec6220a7c8a4fb
# Plot directories inside of the container configured in docker-compose.yml seperated by ;
plot_dirs=/root/plotfile/
# Postgresql connection string
db_connection="database=mydb;username=fedoraAdmin;password=123456;host=localhost;port=5432;"
-----------------------------------------------------------------------------------------------
![1619420410(1)](https://user-images.githubusercontent.com/20960803/116041771-34751a80-a6a0-11eb-8ca9-39e44cc608d7.png)

**Comment by cqcwasd** [comment]
Is this configuration correct?

----------------------------------------------------------------------------------------------------------------
# Name of the pool, can be any string
pool_name=adap123455
# Key of the wallet, keep these secure
wallet_keys=0xa0ea3cb47d31e328976caf396052d217727a5f09c761e2ebc2a17cf8765c9b409b9b1a1fa476d48279e1d9fff6ef75a5
# Keys used for plotting and farming, those are available to the harvesters, do not use the wallet key for this
farmer_keys=0x81a8979ef2604ed706b070140108efbc67c309b3c262f88d04219dd50355aa4d22fa8cb8ea3fc1b933ec6220a7c8a4fb
# Plot directories inside of the container configured in docker-compose.yml seperated by ;
plot_dirs=/root/plotfile/
# Postgresql connection string
db_connection="database=mydb;username=fedoraAdmin;password=123456;host=localhost;port=5432;"
----------------------------------------------------------------------------------------------------------------
![1619420410(1)](https://user-images.githubusercontent.com/20960803/116042011-828a1e00-a6a0-11eb-8098-55c932dc107c.png)

**Comment by cqcwasd** [comment]
Is this configuration correct?
----------------------------------------------------------------------------------------------------------------
# Name of the pool, can be any string
pool_name=adap123455
# Key of the wallet, keep these secure
wallet_keys=0xa0ea3cb47d31e328976caf396052d217727a5f09c761e2ebc2a17cf8765c9b409b9b1a1fa476d48279e1d9fff6ef75a5
# Keys used for plotting and farming, those are available to the harvesters, do not use the wallet key for this
farmer_keys=0x81a8979ef2604ed706b070140108efbc67c309b3c262f88d04219dd50355aa4d22fa8cb8ea3fc1b933ec6220a7c8a4fb
# Plot directories inside of the container configured in docker-compose.yml seperated by ;
plot_dirs=/root/plotfile/
# Postgresql connection string
db_connection="database=mydb;username=fedoraAdmin;password=123456;host=localhost;port=5432;"
![1619420410(1)](https://user-images.githubusercontent.com/20960803/116042358-e4e31e80-a6a0-11eb-89a2-7f9367a3afd7.png)

**Comment by cqcwasd** [comment]
Is this configuration correct?
----------------------------------------------------------------------------------------------------------------
/#
![1619420410(1)](https://user-images.githubusercontent.com/20960803/116042570-2247ac00-a6a1-11eb-9fc9-034cc030e1ad.png)
Name of the pool, can be any string
pool_name=adap123455
/#Key of the wallet, keep these secure
wallet_keys=0xa0ea3cb47d31e328976caf396052d217727a5f09c761e2ebc2a17cf8765c9b409b9b1a1fa476d48279e1d9fff6ef75a5
/#Keys used for plotting and farming, those are available to the harvesters, do not use the wallet key for this
farmer_keys=0x81a8979ef2604ed706b070140108efbc67c309b3c262f88d04219dd50355aa4d22fa8cb8ea3fc1b933ec6220a7c8a4fb
/#Plot directories inside of the container configured in docker-compose.yml seperated by ;
plot_dirs=/root/plotfile/
/#Postgresql connection string
db_connection="database=mydb;username=fedoraAdmin;password=123456;host=localhost;port=5432;"

**Comment by Playwo** [comment]
No and for several reasons.
I have changed the environment file contents on both miner and server since you pulled. If you rebuild your image it will require pulling the new env files.
Moreover you have specified the public keys (I think those are the public keys) but you have to specify your 24 word mnemonic keys.

**Comment by cqcwasd** [comment]
My address needs to be configured, please guide, thank you very much
my pool.env
---------------------------------------------------------------------------------------
/# Name of the pool, can be any string
pool_name=mypool
/# Key of the wallet, keep these secure
wallet_keys="adapt deputy note grit onion thrive shoe super impact sail forum private zero icon aunt assault sibling suffer knife exact beach emerge excuse vendor"
/# Key used to generate plots on plotters
plotting_keys="8c29e73b3f847dcd29b8f324ccb4a3d348864f51f2016ff35b2dfae9a90a7e3e32f53a76f67568419573e71433bf059e"
/# Postgresql connection string
db_connection="database=dbchia;username=postgres;password=123456;host=localhost;port=5432;"
/# Allow user registration
allow_user_registration=false
/# Allow miner creation
allow_miner_creation=false
/# Allow plotter creation
allow_plotter_creation=false
---------------------------------------------------------------------------------------
Operation tips
---------------------------------------------------------------------------------------
/root/.chia/mainnet already exists, no migration action taken
**You need to provide a wallet address!**    
Your wallet address is the "First wallet address" in the following output. Add it to your node.env file (wallet_address=xch...)
Enter the mnemonic you want to use: Added private key with public key fingerprint 2764891946 and mnemonic
adapt deputy note grit onion thrive shoe super impact sail forum private zero icon aunt assault sibling suffer knife exact beach emerge excuse vendor
Showing all private keys:

Fingerprint: 2764891946
Master public key (m): aba9d5e1bc486471c55e6b87a5def421143d94e1f4727109e12fc781ed2fd16382c76c4ecd8c6c211f154ff026011451
Master private key (m): 0354c832bcd20220622affa0bfd7e38096240ac26e04f2744ebf4f987bc955cd
Farmer public key (m/12381/8444/0/0): 9922daac824ba5751a9d600c03a03da98e6730eda1a05cf7904f181ca6b7a6dfee4753baca878c0dce10f16f87e33d3e
Pool public key (m/12381/8444/1/0): 83bb9aa63efc03e36d8484653822f6ba56284ae04aa3f3e78ae61417c6a36f44ab166d2a1334f16b070c4b3cf490edf0
First wallet key (m/12381/8444/2/0): 8c29e73b3f847dcd29b8f324ccb4a3d348864f51f2016ff35b2dfae9a90a7e3e32f53a76f67568419573e71433bf059e
First wallet address: xch154l35u7xsqrjltnq9s4u5p24gc6guqsndhuxsem7gv9l9vy39dasu2a3uj
Aborting...
---------------------------------------------------------------------------------------

**Comment by tancau** [comment]
@Playwo how fix it?

info: ChiaPool.Startup[0]
      Waiting for fullnode to spin up
info: ChiaPool.Startup[0]
      Connection established!
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.IO.IOException: Failed to bind to address http://0.0.0.0:8666: address already in use.
       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (98): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.IO.IOException: Failed to bind to address http://0.0.0.0:8666: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at ChiaPool.Program.Main(String[] args) in /root/ChiaPool/ChiaPool.Server/Program.cs:line 64
   at ChiaPool.Program.<Main>(String[] args)
entrypoint.sh: line 31:  4018 Aborted                 (core dumped) ./ChiaPool.Server

**Comment by tancau** [comment]
@Playwo   Is the server running like this?


Starting ChiaNode ... done
Attaching to ChiaNode
ChiaNode | Chia directory /root/.chia/mainnet
ChiaNode | /root/.chia/mainnet already exists, no migration action taken
ChiaNode | Enter the mnemonic you want to use: Added private key with public key fingerprint 444762997 and mnemonic
ChiaNode | dragon team path deputy goose math mention hurry blue estate replace basic stable term skull wrap fiction second evil type wait below hollow sorry
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for wallet to spin up
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Connection established!
ChiaNode | Wallet height: 0
ChiaNode | Balances, fingerprint: 444762997
ChiaNode | Wallet ID 1 type STANDARD_WALLET
ChiaNode |    -Confirmed: 0 mojo (0.0 xch)
ChiaNode |    -Unconfirmed: 0 mojo (0.0 xch)
ChiaNode |    -Spendable: 0 mojo (0.0 xch)
ChiaNode |    -Pending change: 0 mojo (0.0 xch)
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Waiting for fullnode to spin up
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode |       Connection established!
ChiaNode | info: Microsoft.Hosting.Lifetime[0]
ChiaNode |       Now listening on: http://0.0.0.0:8666
ChiaNode | info: Microsoft.Hosting.Lifetime[0]
ChiaNode |       Application started. Press Ctrl+C to shut down.
ChiaNode | info: Microsoft.Hosting.Lifetime[0]
ChiaNode |       Hosting environment: Production
ChiaNode | info: Microsoft.Hosting.Lifetime[0]
ChiaNode |       Content root path: /root/manager

**Comment by Playwo** [comment]
@tancau Yes this looks good. But change your wallet keys, you leaked them in the logs.

**Comment by Playwo** [comment]
@cqcwasd You also leaked your private keys, change them!
You still have a few things to do: 
- Replace the plotting_keys with actual 24 word keys (different keys than you use for you walllet)
- Rebuild the image (Your image is outdated) & Try again
- When you run into more errors make sure not to leak any private information!

**Comment by cqcwasd** [comment]
@tancau hi， you can provide pool.env configuration file for me to see

**Comment by github332638015** [comment]
ChiaNode | Chia directory /root/.chia/mainnet
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | /root/.chia/mainnet already exists, no migration action taken
ChiaNode | Enter the mnemonic you want to use: Invalid mnemonic length
ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
ChiaNode | Daemon not started yet
ChiaNode | Starting daemon
ChiaNode | chia_wallet: started
ChiaNode | chia_full_node: started
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode | Waiting for wallet to spin up
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode | Connection established!
ChiaNode | No keys loaded. Run 'chia keys generate' or import a key
ChiaNode | info: ChiaPool.Startup[0]
ChiaNode | Waiting for fullnode to spin up

**Comment by nangongchengfeng** [comment]
> ChiaNode | Chia directory /root/.chia/mainnet
> ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
> ChiaNode | /root/.chia/mainnet already exists, no migration action taken
> ChiaNode | Enter the mnemonic you want to use: Invalid mnemonic length
> ChiaNode | No keys are present in the keychain. Generate them with 'chia keys generate'
> ChiaNode | Daemon not started yet
> ChiaNode | Starting daemon
> ChiaNode | chia_wallet: started
> ChiaNode | chia_full_node: started
> ChiaNode | info: ChiaPool.Startup[0]
> ChiaNode | Waiting for wallet to spin up
> ChiaNode | info: ChiaPool.Startup[0]
> ChiaNode | Connection established!
> ChiaNode | No keys loaded. Run 'chia keys generate' or import a key
> ChiaNode | info: ChiaPool.Startup[0]
> ChiaNode | Waiting for fullnode to spin up

Hello, I have this problem now

Chia directory /root/.chia/mainnet
Can't find private CA, creating a new one in /root/.chia/mainnet to generate TLS certificates
No keys are present in the keychain. Generate them with 'chia keys generate'

**Comment by nangongchengfeng** [comment]
Chia directory /root/.chia/mainnet
Can't find private CA, creating a new one in /root/.chia/mainnet to generate TLS certificates
No keys are present in the keychain. Generate them with 'chia keys generate'
To see your keys, run 'chia keys show'
Enter the mnemonic you want to use: Invalid mnemonic length
No keys are present in the keychain. Generate them with 'chia keys generate'
Daemon not started yet
Starting daemon
chia_wallet: started
chia_full_node: started
fail: ChiaPool.Startup[0]
      Config Validation failed: Could not parse value of "allow_plotter_creation" to boolean!
Chia directory /root/.chia/mainnet
No keys are present in the keychain. Generate them with 'chia keys generate'
/root/.chia/mainnet already exists, no migration action taken
Enter the mnemonic you want to use: Invalid mnemonic length
No keys are present in the keychain. Generate them with 'chia keys generate'
Daemon not started yet
Starting daemon
chia_wallet: started
chia_full_node: started

Hello, I have this problem  
docker  Show me the problem
docker No access 。

**Comment by Playwo** [comment]
@github332638015 @nangongchengfeng Both of you have a outdated version of the pool.env file.
Always make sure that you have the latest version of it when you update the docker image.
This is required until I finish 1.0

**Comment by Playwo** [comment]
From now on please create your own issue if you run into any problems, do not put everything into this or any of the other open issues unless it is directly related.
