### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by zx0922** [Playwo/ChiaPool#9]
`root@zs:~/Downloads/ChiaPool/Docker/Server# docker-compose up -d
Creating network "server_default" with the default driver
Creating ChiaNode ...
Creating ChiaNode ... error

ERROR: for ChiaNode  Cannot start service node: driver failed programming external connectivity on endpoint ChiaNode (d228bb26442de0f1786219ba9754f45fb08e37e4b1414a905d7c34ebd2f492f2): Error starting userland proxy: listen tcp4 0.0.0.0:8444: bind: address already in use

ERROR: for node  Cannot start service node: driver failed programming external connectivity on endpoint ChiaNode (d228bb26442de0f1786219ba9754f45fb08e37e4b1414a905d7c34ebd2f492f2): Error starting userland proxy: listen tcp4 0.0.0.0:8444: bind: address already in use
ERROR: Encountered errors while bringing up the project.
`

**Comment by Playwo** [comment]
Looks like the port 8444 on your host machine is already in use. 
The pool server will run a fullnode and it's useful to have it be available on port 8444 even tho you could probably get away with removing that port from the compose file.
I would recommend deciding wether you want to run the pool or the chia fullnode on one machine. Not both
